#:schema https://json.schemastore.org/any.json

env_files = [".env"]
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd"
  entrypoint = ["./tmp/main.exe"]
  delay = 500
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  mode = ""
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false